# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class AssistantResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, response: str=None, context_id: str=None, persona_used: str=None, timestamp: datetime=None):  # noqa: E501
        """AssistantResponse - a model defined in Swagger

        :param response: The response of this AssistantResponse.  # noqa: E501
        :type response: str
        :param context_id: The context_id of this AssistantResponse.  # noqa: E501
        :type context_id: str
        :param persona_used: The persona_used of this AssistantResponse.  # noqa: E501
        :type persona_used: str
        :param timestamp: The timestamp of this AssistantResponse.  # noqa: E501
        :type timestamp: datetime
        """
        self.swagger_types = {
            'response': str,
            'context_id': str,
            'persona_used': str,
            'timestamp': datetime
        }

        self.attribute_map = {
            'response': 'response',
            'context_id': 'context_id',
            'persona_used': 'persona_used',
            'timestamp': 'timestamp'
        }
        self._response = response
        self._context_id = context_id
        self._persona_used = persona_used
        self._timestamp = timestamp

    @classmethod
    def from_dict(cls, dikt) -> 'AssistantResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AssistantResponse of this AssistantResponse.  # noqa: E501
        :rtype: AssistantResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def response(self) -> str:
        """Gets the response of this AssistantResponse.


        :return: The response of this AssistantResponse.
        :rtype: str
        """
        return self._response

    @response.setter
    def response(self, response: str):
        """Sets the response of this AssistantResponse.


        :param response: The response of this AssistantResponse.
        :type response: str
        """

        self._response = response

    @property
    def context_id(self) -> str:
        """Gets the context_id of this AssistantResponse.

        ID of the conversational context  # noqa: E501

        :return: The context_id of this AssistantResponse.
        :rtype: str
        """
        return self._context_id

    @context_id.setter
    def context_id(self, context_id: str):
        """Sets the context_id of this AssistantResponse.

        ID of the conversational context  # noqa: E501

        :param context_id: The context_id of this AssistantResponse.
        :type context_id: str
        """

        self._context_id = context_id

    @property
    def persona_used(self) -> str:
        """Gets the persona_used of this AssistantResponse.

        Persona identifier used in the interaction  # noqa: E501

        :return: The persona_used of this AssistantResponse.
        :rtype: str
        """
        return self._persona_used

    @persona_used.setter
    def persona_used(self, persona_used: str):
        """Sets the persona_used of this AssistantResponse.

        Persona identifier used in the interaction  # noqa: E501

        :param persona_used: The persona_used of this AssistantResponse.
        :type persona_used: str
        """

        self._persona_used = persona_used

    @property
    def timestamp(self) -> datetime:
        """Gets the timestamp of this AssistantResponse.

        ISO 8601 timestamp of the response  # noqa: E501

        :return: The timestamp of this AssistantResponse.
        :rtype: datetime
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp: datetime):
        """Sets the timestamp of this AssistantResponse.

        ISO 8601 timestamp of the response  # noqa: E501

        :param timestamp: The timestamp of this AssistantResponse.
        :type timestamp: datetime
        """

        self._timestamp = timestamp
