# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ChatcompletionsResponseFormat(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, type: str=None):  # noqa: E501
        """ChatcompletionsResponseFormat - a model defined in Swagger

        :param type: The type of this ChatcompletionsResponseFormat.  # noqa: E501
        :type type: str
        """
        self.swagger_types = {
            'type': str
        }

        self.attribute_map = {
            'type': 'type'
        }
        self._type = type

    @classmethod
    def from_dict(cls, dikt) -> 'ChatcompletionsResponseFormat':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The chatcompletions_response_format of this ChatcompletionsResponseFormat.  # noqa: E501
        :rtype: ChatcompletionsResponseFormat
        """
        return util.deserialize_model(dikt, cls)

    @property
    def type(self) -> str:
        """Gets the type of this ChatcompletionsResponseFormat.


        :return: The type of this ChatcompletionsResponseFormat.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this ChatcompletionsResponseFormat.


        :param type: The type of this ChatcompletionsResponseFormat.
        :type type: str
        """
        allowed_values = ["json_object", "text"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"
                .format(type, allowed_values)
            )

        self._type = type
