# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class DashboardLayoutPosition(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, x: int=None, y: int=None, width: int=None, height: int=None):  # noqa: E501
        """DashboardLayoutPosition - a model defined in Swagger

        :param x: The x of this DashboardLayoutPosition.  # noqa: E501
        :type x: int
        :param y: The y of this DashboardLayoutPosition.  # noqa: E501
        :type y: int
        :param width: The width of this DashboardLayoutPosition.  # noqa: E501
        :type width: int
        :param height: The height of this DashboardLayoutPosition.  # noqa: E501
        :type height: int
        """
        self.swagger_types = {
            'x': int,
            'y': int,
            'width': int,
            'height': int
        }

        self.attribute_map = {
            'x': 'x',
            'y': 'y',
            'width': 'width',
            'height': 'height'
        }
        self._x = x
        self._y = y
        self._width = width
        self._height = height

    @classmethod
    def from_dict(cls, dikt) -> 'DashboardLayoutPosition':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DashboardLayout_position of this DashboardLayoutPosition.  # noqa: E501
        :rtype: DashboardLayoutPosition
        """
        return util.deserialize_model(dikt, cls)

    @property
    def x(self) -> int:
        """Gets the x of this DashboardLayoutPosition.


        :return: The x of this DashboardLayoutPosition.
        :rtype: int
        """
        return self._x

    @x.setter
    def x(self, x: int):
        """Sets the x of this DashboardLayoutPosition.


        :param x: The x of this DashboardLayoutPosition.
        :type x: int
        """

        self._x = x

    @property
    def y(self) -> int:
        """Gets the y of this DashboardLayoutPosition.


        :return: The y of this DashboardLayoutPosition.
        :rtype: int
        """
        return self._y

    @y.setter
    def y(self, y: int):
        """Sets the y of this DashboardLayoutPosition.


        :param y: The y of this DashboardLayoutPosition.
        :type y: int
        """

        self._y = y

    @property
    def width(self) -> int:
        """Gets the width of this DashboardLayoutPosition.


        :return: The width of this DashboardLayoutPosition.
        :rtype: int
        """
        return self._width

    @width.setter
    def width(self, width: int):
        """Sets the width of this DashboardLayoutPosition.


        :param width: The width of this DashboardLayoutPosition.
        :type width: int
        """

        self._width = width

    @property
    def height(self) -> int:
        """Gets the height of this DashboardLayoutPosition.


        :return: The height of this DashboardLayoutPosition.
        :rtype: int
        """
        return self._height

    @height.setter
    def height(self, height: int):
        """Sets the height of this DashboardLayoutPosition.


        :param height: The height of this DashboardLayoutPosition.
        :type height: int
        """

        self._height = height
