# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class DataenrichmentBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, data: List[object]=None, enrichment_sources: List[str]=None):  # noqa: E501
        """DataenrichmentBody - a model defined in Swagger

        :param data: The data of this DataenrichmentBody.  # noqa: E501
        :type data: List[object]
        :param enrichment_sources: The enrichment_sources of this DataenrichmentBody.  # noqa: E501
        :type enrichment_sources: List[str]
        """
        self.swagger_types = {
            'data': List[object],
            'enrichment_sources': List[str]
        }

        self.attribute_map = {
            'data': 'data',
            'enrichment_sources': 'enrichment_sources'
        }
        self._data = data
        self._enrichment_sources = enrichment_sources

    @classmethod
    def from_dict(cls, dikt) -> 'DataenrichmentBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The dataenrichment_body of this DataenrichmentBody.  # noqa: E501
        :rtype: DataenrichmentBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> List[object]:
        """Gets the data of this DataenrichmentBody.


        :return: The data of this DataenrichmentBody.
        :rtype: List[object]
        """
        return self._data

    @data.setter
    def data(self, data: List[object]):
        """Sets the data of this DataenrichmentBody.


        :param data: The data of this DataenrichmentBody.
        :type data: List[object]
        """

        self._data = data

    @property
    def enrichment_sources(self) -> List[str]:
        """Gets the enrichment_sources of this DataenrichmentBody.


        :return: The enrichment_sources of this DataenrichmentBody.
        :rtype: List[str]
        """
        return self._enrichment_sources

    @enrichment_sources.setter
    def enrichment_sources(self, enrichment_sources: List[str]):
        """Sets the enrichment_sources of this DataenrichmentBody.


        :param enrichment_sources: The enrichment_sources of this DataenrichmentBody.
        :type enrichment_sources: List[str]
        """

        self._enrichment_sources = enrichment_sources
