# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class EmbeddingResponseUsage(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, prompt_tokens: int=None, total_tokens: int=None):  # noqa: E501
        """EmbeddingResponseUsage - a model defined in Swagger

        :param prompt_tokens: The prompt_tokens of this EmbeddingResponseUsage.  # noqa: E501
        :type prompt_tokens: int
        :param total_tokens: The total_tokens of this EmbeddingResponseUsage.  # noqa: E501
        :type total_tokens: int
        """
        self.swagger_types = {
            'prompt_tokens': int,
            'total_tokens': int
        }

        self.attribute_map = {
            'prompt_tokens': 'prompt_tokens',
            'total_tokens': 'total_tokens'
        }
        self._prompt_tokens = prompt_tokens
        self._total_tokens = total_tokens

    @classmethod
    def from_dict(cls, dikt) -> 'EmbeddingResponseUsage':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The EmbeddingResponse_usage of this EmbeddingResponseUsage.  # noqa: E501
        :rtype: EmbeddingResponseUsage
        """
        return util.deserialize_model(dikt, cls)

    @property
    def prompt_tokens(self) -> int:
        """Gets the prompt_tokens of this EmbeddingResponseUsage.


        :return: The prompt_tokens of this EmbeddingResponseUsage.
        :rtype: int
        """
        return self._prompt_tokens

    @prompt_tokens.setter
    def prompt_tokens(self, prompt_tokens: int):
        """Sets the prompt_tokens of this EmbeddingResponseUsage.


        :param prompt_tokens: The prompt_tokens of this EmbeddingResponseUsage.
        :type prompt_tokens: int
        """

        self._prompt_tokens = prompt_tokens

    @property
    def total_tokens(self) -> int:
        """Gets the total_tokens of this EmbeddingResponseUsage.


        :return: The total_tokens of this EmbeddingResponseUsage.
        :rtype: int
        """
        return self._total_tokens

    @total_tokens.setter
    def total_tokens(self, total_tokens: int):
        """Sets the total_tokens of this EmbeddingResponseUsage.


        :param total_tokens: The total_tokens of this EmbeddingResponseUsage.
        :type total_tokens: int
        """

        self._total_tokens = total_tokens
