# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class EmbeddingResponseData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, object: str=None, embedding: List[float]=None, index: int=None):  # noqa: E501
        """EmbeddingResponseData - a model defined in Swagger

        :param object: The object of this EmbeddingResponseData.  # noqa: E501
        :type object: str
        :param embedding: The embedding of this EmbeddingResponseData.  # noqa: E501
        :type embedding: List[float]
        :param index: The index of this EmbeddingResponseData.  # noqa: E501
        :type index: int
        """
        self.swagger_types = {
            'object': str,
            'embedding': List[float],
            'index': int
        }

        self.attribute_map = {
            'object': 'object',
            'embedding': 'embedding',
            'index': 'index'
        }
        self._object = object
        self._embedding = embedding
        self._index = index

    @classmethod
    def from_dict(cls, dikt) -> 'EmbeddingResponseData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The EmbeddingResponse_data of this EmbeddingResponseData.  # noqa: E501
        :rtype: EmbeddingResponseData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def object(self) -> str:
        """Gets the object of this EmbeddingResponseData.


        :return: The object of this EmbeddingResponseData.
        :rtype: str
        """
        return self._object

    @object.setter
    def object(self, object: str):
        """Sets the object of this EmbeddingResponseData.


        :param object: The object of this EmbeddingResponseData.
        :type object: str
        """
        allowed_values = ["embedding"]  # noqa: E501
        if object not in allowed_values:
            raise ValueError(
                "Invalid value for `object` ({0}), must be one of {1}"
                .format(object, allowed_values)
            )

        self._object = object

    @property
    def embedding(self) -> List[float]:
        """Gets the embedding of this EmbeddingResponseData.


        :return: The embedding of this EmbeddingResponseData.
        :rtype: List[float]
        """
        return self._embedding

    @embedding.setter
    def embedding(self, embedding: List[float]):
        """Sets the embedding of this EmbeddingResponseData.


        :param embedding: The embedding of this EmbeddingResponseData.
        :type embedding: List[float]
        """

        self._embedding = embedding

    @property
    def index(self) -> int:
        """Gets the index of this EmbeddingResponseData.


        :return: The index of this EmbeddingResponseData.
        :rtype: int
        """
        return self._index

    @index.setter
    def index(self, index: int):
        """Sets the index of this EmbeddingResponseData.


        :param index: The index of this EmbeddingResponseData.
        :type index: int
        """

        self._index = index
