# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class FeedbackSubmissionUserInfo(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, user_id: str=None, email: str=None):  # noqa: E501
        """FeedbackSubmissionUserInfo - a model defined in Swagger

        :param user_id: The user_id of this FeedbackSubmissionUserInfo.  # noqa: E501
        :type user_id: str
        :param email: The email of this FeedbackSubmissionUserInfo.  # noqa: E501
        :type email: str
        """
        self.swagger_types = {
            'user_id': str,
            'email': str
        }

        self.attribute_map = {
            'user_id': 'user_id',
            'email': 'email'
        }
        self._user_id = user_id
        self._email = email

    @classmethod
    def from_dict(cls, dikt) -> 'FeedbackSubmissionUserInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The FeedbackSubmission_user_info of this FeedbackSubmissionUserInfo.  # noqa: E501
        :rtype: FeedbackSubmissionUserInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user_id(self) -> str:
        """Gets the user_id of this FeedbackSubmissionUserInfo.


        :return: The user_id of this FeedbackSubmissionUserInfo.
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id: str):
        """Sets the user_id of this FeedbackSubmissionUserInfo.


        :param user_id: The user_id of this FeedbackSubmissionUserInfo.
        :type user_id: str
        """

        self._user_id = user_id

    @property
    def email(self) -> str:
        """Gets the email of this FeedbackSubmissionUserInfo.


        :return: The email of this FeedbackSubmissionUserInfo.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """Sets the email of this FeedbackSubmissionUserInfo.


        :param email: The email of this FeedbackSubmissionUserInfo.
        :type email: str
        """

        self._email = email
