# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.function_definition_parameters import FunctionDefinitionParameters  # noqa: F401,E501
from swagger_server import util


class FunctionDefinition(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, name: str=None, description: str=None, parameters: FunctionDefinitionParameters=None):  # noqa: E501
        """FunctionDefinition - a model defined in Swagger

        :param name: The name of this FunctionDefinition.  # noqa: E501
        :type name: str
        :param description: The description of this FunctionDefinition.  # noqa: E501
        :type description: str
        :param parameters: The parameters of this FunctionDefinition.  # noqa: E501
        :type parameters: FunctionDefinitionParameters
        """
        self.swagger_types = {
            'name': str,
            'description': str,
            'parameters': FunctionDefinitionParameters
        }

        self.attribute_map = {
            'name': 'name',
            'description': 'description',
            'parameters': 'parameters'
        }
        self._name = name
        self._description = description
        self._parameters = parameters

    @classmethod
    def from_dict(cls, dikt) -> 'FunctionDefinition':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The FunctionDefinition of this FunctionDefinition.  # noqa: E501
        :rtype: FunctionDefinition
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this FunctionDefinition.


        :return: The name of this FunctionDefinition.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this FunctionDefinition.


        :param name: The name of this FunctionDefinition.
        :type name: str
        """

        self._name = name

    @property
    def description(self) -> str:
        """Gets the description of this FunctionDefinition.


        :return: The description of this FunctionDefinition.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this FunctionDefinition.


        :param description: The description of this FunctionDefinition.
        :type description: str
        """

        self._description = description

    @property
    def parameters(self) -> FunctionDefinitionParameters:
        """Gets the parameters of this FunctionDefinition.


        :return: The parameters of this FunctionDefinition.
        :rtype: FunctionDefinitionParameters
        """
        return self._parameters

    @parameters.setter
    def parameters(self, parameters: FunctionDefinitionParameters):
        """Sets the parameters of this FunctionDefinition.


        :param parameters: The parameters of this FunctionDefinition.
        :type parameters: FunctionDefinitionParameters
        """

        self._parameters = parameters
