# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.image_generation_response_data import ImageGenerationResponseData  # noqa: F401,E501
from swagger_server import util


class ImageGenerationResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, created: int=None, data: List[ImageGenerationResponseData]=None):  # noqa: E501
        """ImageGenerationResponse - a model defined in Swagger

        :param created: The created of this ImageGenerationResponse.  # noqa: E501
        :type created: int
        :param data: The data of this ImageGenerationResponse.  # noqa: E501
        :type data: List[ImageGenerationResponseData]
        """
        self.swagger_types = {
            'created': int,
            'data': List[ImageGenerationResponseData]
        }

        self.attribute_map = {
            'created': 'created',
            'data': 'data'
        }
        self._created = created
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'ImageGenerationResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ImageGenerationResponse of this ImageGenerationResponse.  # noqa: E501
        :rtype: ImageGenerationResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def created(self) -> int:
        """Gets the created of this ImageGenerationResponse.


        :return: The created of this ImageGenerationResponse.
        :rtype: int
        """
        return self._created

    @created.setter
    def created(self, created: int):
        """Sets the created of this ImageGenerationResponse.


        :param created: The created of this ImageGenerationResponse.
        :type created: int
        """

        self._created = created

    @property
    def data(self) -> List[ImageGenerationResponseData]:
        """Gets the data of this ImageGenerationResponse.


        :return: The data of this ImageGenerationResponse.
        :rtype: List[ImageGenerationResponseData]
        """
        return self._data

    @data.setter
    def data(self, data: List[ImageGenerationResponseData]):
        """Sets the data of this ImageGenerationResponse.


        :param data: The data of this ImageGenerationResponse.
        :type data: List[ImageGenerationResponseData]
        """

        self._data = data
