# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ImagesEditsBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, image: str=None, mask: str=None, prompts: str=None, n: int=1, size: str=None):  # noqa: E501
        """ImagesEditsBody - a model defined in Swagger

        :param image: The image of this ImagesEditsBody.  # noqa: E501
        :type image: str
        :param mask: The mask of this ImagesEditsBody.  # noqa: E501
        :type mask: str
        :param prompts: The prompts of this ImagesEditsBody.  # noqa: E501
        :type prompts: str
        :param n: The n of this ImagesEditsBody.  # noqa: E501
        :type n: int
        :param size: The size of this ImagesEditsBody.  # noqa: E501
        :type size: str
        """
        self.swagger_types = {
            'image': str,
            'mask': str,
            'prompts': str,
            'n': int,
            'size': str
        }

        self.attribute_map = {
            'image': 'image',
            'mask': 'mask',
            'prompts': 'prompts',
            'n': 'n',
            'size': 'size'
        }
        self._image = image
        self._mask = mask
        self._prompts = prompts
        self._n = n
        self._size = size

    @classmethod
    def from_dict(cls, dikt) -> 'ImagesEditsBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The images_edits_body of this ImagesEditsBody.  # noqa: E501
        :rtype: ImagesEditsBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def image(self) -> str:
        """Gets the image of this ImagesEditsBody.


        :return: The image of this ImagesEditsBody.
        :rtype: str
        """
        return self._image

    @image.setter
    def image(self, image: str):
        """Sets the image of this ImagesEditsBody.


        :param image: The image of this ImagesEditsBody.
        :type image: str
        """
        if image is None:
            raise ValueError("Invalid value for `image`, must not be `None`")  # noqa: E501

        self._image = image

    @property
    def mask(self) -> str:
        """Gets the mask of this ImagesEditsBody.


        :return: The mask of this ImagesEditsBody.
        :rtype: str
        """
        return self._mask

    @mask.setter
    def mask(self, mask: str):
        """Sets the mask of this ImagesEditsBody.


        :param mask: The mask of this ImagesEditsBody.
        :type mask: str
        """

        self._mask = mask

    @property
    def prompts(self) -> str:
        """Gets the prompts of this ImagesEditsBody.


        :return: The prompts of this ImagesEditsBody.
        :rtype: str
        """
        return self._prompts

    @prompts.setter
    def prompts(self, prompts: str):
        """Sets the prompts of this ImagesEditsBody.


        :param prompts: The prompts of this ImagesEditsBody.
        :type prompts: str
        """

        self._prompts = prompts

    @property
    def n(self) -> int:
        """Gets the n of this ImagesEditsBody.


        :return: The n of this ImagesEditsBody.
        :rtype: int
        """
        return self._n

    @n.setter
    def n(self, n: int):
        """Sets the n of this ImagesEditsBody.


        :param n: The n of this ImagesEditsBody.
        :type n: int
        """

        self._n = n

    @property
    def size(self) -> str:
        """Gets the size of this ImagesEditsBody.


        :return: The size of this ImagesEditsBody.
        :rtype: str
        """
        return self._size

    @size.setter
    def size(self, size: str):
        """Sets the size of this ImagesEditsBody.


        :param size: The size of this ImagesEditsBody.
        :type size: str
        """
        allowed_values = ["256x256", "512x512", "1024x1024"]  # noqa: E501
        if size not in allowed_values:
            raise ValueError(
                "Invalid value for `size` ({0}), must be one of {1}"
                .format(size, allowed_values)
            )

        self._size = size
