# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ImageGenerationResponseData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, url: str=None, b64_json: str=None, revised_prompt: str=None):  # noqa: E501
        """ImageGenerationResponseData - a model defined in Swagger

        :param url: The url of this ImageGenerationResponseData.  # noqa: E501
        :type url: str
        :param b64_json: The b64_json of this ImageGenerationResponseData.  # noqa: E501
        :type b64_json: str
        :param revised_prompt: The revised_prompt of this ImageGenerationResponseData.  # noqa: E501
        :type revised_prompt: str
        """
        self.swagger_types = {
            'url': str,
            'b64_json': str,
            'revised_prompt': str
        }

        self.attribute_map = {
            'url': 'url',
            'b64_json': 'b64_json',
            'revised_prompt': 'revised_prompt'
        }
        self._url = url
        self._b64_json = b64_json
        self._revised_prompt = revised_prompt

    @classmethod
    def from_dict(cls, dikt) -> 'ImageGenerationResponseData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ImageGenerationResponse_data of this ImageGenerationResponseData.  # noqa: E501
        :rtype: ImageGenerationResponseData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def url(self) -> str:
        """Gets the url of this ImageGenerationResponseData.


        :return: The url of this ImageGenerationResponseData.
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url: str):
        """Sets the url of this ImageGenerationResponseData.


        :param url: The url of this ImageGenerationResponseData.
        :type url: str
        """

        self._url = url

    @property
    def b64_json(self) -> str:
        """Gets the b64_json of this ImageGenerationResponseData.


        :return: The b64_json of this ImageGenerationResponseData.
        :rtype: str
        """
        return self._b64_json

    @b64_json.setter
    def b64_json(self, b64_json: str):
        """Sets the b64_json of this ImageGenerationResponseData.


        :param b64_json: The b64_json of this ImageGenerationResponseData.
        :type b64_json: str
        """

        self._b64_json = b64_json

    @property
    def revised_prompt(self) -> str:
        """Gets the revised_prompt of this ImageGenerationResponseData.


        :return: The revised_prompt of this ImageGenerationResponseData.
        :rtype: str
        """
        return self._revised_prompt

    @revised_prompt.setter
    def revised_prompt(self, revised_prompt: str):
        """Sets the revised_prompt of this ImageGenerationResponseData.


        :param revised_prompt: The revised_prompt of this ImageGenerationResponseData.
        :type revised_prompt: str
        """

        self._revised_prompt = revised_prompt
