# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse200(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, status: str=None, results: object=None):  # noqa: E501
        """InlineResponse200 - a model defined in Swagger

        :param status: The status of this InlineResponse200.  # noqa: E501
        :type status: str
        :param results: The results of this InlineResponse200.  # noqa: E501
        :type results: object
        """
        self.swagger_types = {
            'status': str,
            'results': object
        }

        self.attribute_map = {
            'status': 'status',
            'results': 'results'
        }
        self._status = status
        self._results = results

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200 of this InlineResponse200.  # noqa: E501
        :rtype: InlineResponse200
        """
        return util.deserialize_model(dikt, cls)

    @property
    def status(self) -> str:
        """Gets the status of this InlineResponse200.


        :return: The status of this InlineResponse200.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this InlineResponse200.


        :param status: The status of this InlineResponse200.
        :type status: str
        """

        self._status = status

    @property
    def results(self) -> object:
        """Gets the results of this InlineResponse200.


        :return: The results of this InlineResponse200.
        :rtype: object
        """
        return self._results

    @results.setter
    def results(self, results: object):
        """Sets the results of this InlineResponse200.


        :param results: The results of this InlineResponse200.
        :type results: object
        """

        self._results = results
