# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class OracleInsightFactors(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, factor: str=None, weight: float=None):  # noqa: E501
        """OracleInsightFactors - a model defined in Swagger

        :param factor: The factor of this OracleInsightFactors.  # noqa: E501
        :type factor: str
        :param weight: The weight of this OracleInsightFactors.  # noqa: E501
        :type weight: float
        """
        self.swagger_types = {
            'factor': str,
            'weight': float
        }

        self.attribute_map = {
            'factor': 'factor',
            'weight': 'weight'
        }
        self._factor = factor
        self._weight = weight

    @classmethod
    def from_dict(cls, dikt) -> 'OracleInsightFactors':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The OracleInsight_factors of this OracleInsightFactors.  # noqa: E501
        :rtype: OracleInsightFactors
        """
        return util.deserialize_model(dikt, cls)

    @property
    def factor(self) -> str:
        """Gets the factor of this OracleInsightFactors.


        :return: The factor of this OracleInsightFactors.
        :rtype: str
        """
        return self._factor

    @factor.setter
    def factor(self, factor: str):
        """Sets the factor of this OracleInsightFactors.


        :param factor: The factor of this OracleInsightFactors.
        :type factor: str
        """

        self._factor = factor

    @property
    def weight(self) -> float:
        """Gets the weight of this OracleInsightFactors.


        :return: The weight of this OracleInsightFactors.
        :rtype: float
        """
        return self._weight

    @weight.setter
    def weight(self, weight: float):
        """Sets the weight of this OracleInsightFactors.


        :param weight: The weight of this OracleInsightFactors.
        :type weight: float
        """

        self._weight = weight
