# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class SessionRevokeBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, session_id: str=None, user_id: str=None):  # noqa: E501
        """SessionRevokeBody - a model defined in Swagger

        :param session_id: The session_id of this SessionRevokeBody.  # noqa: E501
        :type session_id: str
        :param user_id: The user_id of this SessionRevokeBody.  # noqa: E501
        :type user_id: str
        """
        self.swagger_types = {
            'session_id': str,
            'user_id': str
        }

        self.attribute_map = {
            'session_id': 'session_id',
            'user_id': 'user_id'
        }
        self._session_id = session_id
        self._user_id = user_id

    @classmethod
    def from_dict(cls, dikt) -> 'SessionRevokeBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The session_revoke_body of this SessionRevokeBody.  # noqa: E501
        :rtype: SessionRevokeBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def session_id(self) -> str:
        """Gets the session_id of this SessionRevokeBody.


        :return: The session_id of this SessionRevokeBody.
        :rtype: str
        """
        return self._session_id

    @session_id.setter
    def session_id(self, session_id: str):
        """Sets the session_id of this SessionRevokeBody.


        :param session_id: The session_id of this SessionRevokeBody.
        :type session_id: str
        """

        self._session_id = session_id

    @property
    def user_id(self) -> str:
        """Gets the user_id of this SessionRevokeBody.


        :return: The user_id of this SessionRevokeBody.
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id: str):
        """Sets the user_id of this SessionRevokeBody.


        :param user_id: The user_id of this SessionRevokeBody.
        :type user_id: str
        """

        self._user_id = user_id
